---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: effilab
spec:
  selector:
    matchLabels:
      run: debian
  template:
    metadata:
      labels:
        run: debian
    spec:
      containers:
      - name: debian
        image: gcr.io/hebe-299715/debian
        ports:
        - name: ssh
          containerPort: 22
