---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-cluster-deployment
  namespace: hebe
spec:
  selector:
    matchLabels:
      run: debian-sid
  template:
    metadata:
      labels:
        run: debian-sid
    spec:
      containers:
      - name: debian-sid
        image: gcr.io/hebe-001/debian-sid
        ports:
        - name: ssh
          containerPort: 22
        - name: logstash-tcp
          containerPort: 4000
        - name: logstash-beats
          containerPort: 5044
        - name: logstash-gelf
          containerPort: 12201
        - name: nginx
          containerPort: 8000
