---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: hebe
spec:
  selector:
    matchLabels:
      run: debian-sid
  template:
    metadata:
      labels:
        run: debian-sid
    spec:
      containers:
      - name: debian-sid
        image: gcr.io/hebe-001/debian-sid
        ports:
        - name: ssh
          containerPort: 22
        - name: web
          containerPort: 8000
