---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: hebe
spec:
  type: LoadBalancer
  loadBalancerIP: 35.228.85.147
  selector:
    run: debian-sid
  ports:
    - port: 22
      name: ssh
      targetPort: 22
    - port: 80
      name: nginx
      targetPort: 8000
