---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: hebe
spec:
  type: LoadBalancer
  loadBalancerIP: 35.228.103.86
  selector:
    run: debian-sid
  ports:
    - port: 80
      name: nginx
      targetPort: 8000
