---
apiVersion: v1
kind: Service
metadata:
  name: app-loadbalancer
  namespace: hebe
spec:
  type: LoadBalancer
  selector:
    run: debian-sid
  ports:
    - port: 8000
      name: nginx
      targetPort: 80
